course_create:
    pattern: /course/create
    defaults: { _controller: RotisCourseMakerBundle:Course:create }

course_edit:
    pattern: /course/edit/{id}
    defaults: { _controller: RotisCourseMakerBundle:Course:edit }
    requirements:
        id: \d+
course_remove:
    pattern: /course/remove/{id}
    defaults: { _controller: RotisCourseMakerBundle:Course:remove }
    requirements:
        id: \d+

course_resultat:
    pattern: /edition/resultats/{id}
    defaults: { _controller: RotisCourseMakerBundle:Course:resultats }
    requirements:
        id: \d+