edition_numero:
    pattern: /{numero}
    defaults: { _controller: RotisCourseMakerBundle:Edition:numero }

edition_create:
    pattern: /create
    defaults: { _controller: RotisCourseMakerBundle:CRUD:createEdition }

edition_edit:
    pattern: /edit/{id}
    defaults: { _controller: RotisCourseMakerBundle:CRUD:editEdition }
    requirements:
        id: \d+

edition_remove:
    pattern: /remove/{id}
    defaults: { _controller: RotisCourseMakerBundle:CRUD:removeEdition }
    requirements:
        id: \d+
