register:
    pattern: /register
    defaults: { _controller: RotisCourseMakerBundle:Equipe:register }

create:
    pattern: /create
    defaults: { _controller: RotisCourseMakerBundle:Equipe:create }
    requirements:
        _method: POST

account:
    pattern: /{id}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:edit }
    requirements:
        id: \d+

equipe_remove_joueur:
    pattern: /{id}/{idjoueur}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:remove_joueur}
    requirements:
        id: \d+
        idjoueur: \d+

equipe_set_optional_data:
    pattern: /optional/{id}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:setOptionalData }
    options:
        expose: true
    requirements:
        id: \d+
        _method: POST

upload:
    pattern: /upload/{joueur}/{type}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:upload }
    options:
        expose: true
    requirements:
        joueur: \d+
        type: certif|carte
        _method: POST

pay:
    pattern: /pay/{equipe}/{joueurs}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:pay }
    options:
        expose: true
    requirements:
      equipe: \d+

pay_check:
    pattern: /pay/{equipe}/check/{id}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:payCheck }
    requirements:
      equipe: \d+
      id: \d+

team_pay_check:
    pattern: /pay/{equipe}/check/all
    defaults: { _controller: RotisCourseMakerBundle:Equipe:teamCheck }
    requirements:
      equipe: \d+