Rotis\CourseMakerBundle\Entity\Certif:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        path:
            type: string
            length: 255
            nullable: true
        file:

        filename:
            type: string
            length: 255
            nullable: true
    oneToOne:
        joueur:
          targetEntity: Joueur
          inversedBy: certif

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
