Rotis\CourseMakerBundle\Entity\User:
  type: entity
  table: null
  repositoryClass: Rotis\CourseMakerBundle\Entity\UserRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    categorie:
      type: object
    moyen:
      type: string
      length: 255
    competition:
      type: string
      length: 255
  lifecycleCallbacks: {  }
