generator: admingenerator.generator.doctrine
params:
    model: Rotis\CourseMakerBundle\Entity\Course
    namespace_prefix: Rotis
    bundle_name: CourseMakerBundle
    fields: ~

builders:
    list:
        params:
            title: List for CourseMakerBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New object for CourseMakerBundle
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: YourModel.title }|"
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: YourModel.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    delete: ~
