<?php

namespace Rotis\CourseMakerBundle\Tests\Controller;

use atoum\AtoumBundle\Test\Units\WebTestCase;
use atoum\AtoumBundle\Test\Controller\ControllerTest;

/*
 * Here we will test for all public pages,
 * generated by any controller...
 */

class CourseMakerController extends ControllerTest
{
    public function testAccueil()
    {
        $this
            ->request()
            ->GET('/')
            ->hasStatus(200)
            ->hasHeader('Content-Type', 'text/html; charset=UTF-8')
            ->crawler
            ->hasElement('.hero-unit') # main title, "hero" block
            ->end()
            ->hasElement('a')
            ->withContent('Inscription')
            ->end()
            ->hasElement('a')
            ->withContent('Connexion')
            ->end()
            ->hasElement('a')
            ->withContent('Contact')
            ->end();
    }

    public function test404()
    {
        $this
            ->request()
            ->GET('/bloorp')
            ->hasStatus(404);
    }

    public function testContact()
    {
        $this
            ->request()
            ->GET('/contact')
            ->hasStatus(200)
            ->hasHeader('Content-Type', 'text/html; charset=UTF-8')
            ->crawler
            ->hasElement('.hero-unit') # main title, "hero" block
            ->end()
            ->hasElement('a')
            ->withContent('Accueil')
            ->end();
    }

    // temporary page, empty at the moment
    /*public function testInfosPratiques()
    {
        $this
            ->request()
                ->GET('/infos_pratiques')
                ->hasStatus(200)
                ->hasHeader('Content-Type', 'text/html; charset=UTF-8')
                ->crawler
                    ->hasElement('.hero-unit') # main title, "hero" block
                    ->end()
                    ->hasElement('a')
                        ->withContent('Accueil')
                    ->end()
                    ->hasElement('a')
                        ->withContent('Contact')
                    ->end()
        ;
    }*/
}