account:
    pattern: /{id}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:edit_equipe }
    requirements:
        id: \d+
equipe_remove_joueur:
    pattern: /{id}/{idjoueur}
    defaults: { _controller: RotisCourseMakerBundle:Equipe:remove_joueur}
    requirements:
        id: \d+
        idjoueur: \d+
