<?php

namespace Rotis\CourseMakerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    public function findLike($mot,$numero = null)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.nom LIKE :mot')
            ->orderBy('c.nom', 'ASC')
            ->setParameter('mot', '%'.$mot.'%');

        if($numero)
        {
            $qb->join('c.edition', 'e')
                ->andWhere('e.numero = :numero')
                ->setParameter('numero',$numero);
        }

        $query = $qb->getQuery();
        $courses = $query->getResult();
        return $courses;
    }


    public function findTypeWithCourse($id)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.type = :idtype')
            ->setParameter('idtype', $id)
            ->groupBy('c.type');

        $query = $qb->getQuery();
        $courses = $query->getResult();
        return $courses;
    }

    public function findByEdition($numero)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->join('c.edition','e')
            ->where('e.numero = :numero')
            ->setParameter('numero',$numero);
        $query = $qb->getQuery();
        $courses = $query->getResult();
        return $courses;
    }
}
