<?php

namespace Rotis\CourseMakerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    public function findLike($mot)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.nom LIKE :mot')
            ->orderBy('e.nom', 'ASC')
            ->setParameter('mot', '%'.$mot.'%');

        $query = $qb->getQuery();
        $courses = $query->getResult();
        return $courses;
    }


    public function findTypeWithCourse($id)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.type = :idtype')
            ->setParameter('idtype', $id)
            ->groupBy('c.type');

        $query = $qb->getQuery();
        $courses = $query->getResult();
        return $courses;
    }

    public function findByEdition($id)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.edition = :idEdition')
            ->setParameter('idEdition',$id);
        $query = $qb->getQuery();
        $courses = $query->getResult();
        return $courses;
    }
}
