<?php

namespace Rotis\CourseMakerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends EntityRepository
{
}
