<?php

namespace Rotis\CourseMakerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifRepository extends EntityRepository
{
    public function findTarifByIdCourse($id)
    {
        $qb = $this
            ->createQueryBuilder('t')
            ->where('t.course =:id')
            ->setParameter('id', $id);
        $query = $qb->getQuery();
        $prix = $query->getResult();
        return $prix;
    }
}
